#!/usr/bin/sh
gcc -o assembler assembler.c
assembler test-suite/add.tk
assembler test-suite/addi.tk
assembler test-suite/sub.tk
assembler test-suite/subi.tk
assembler test-suite/mul.tk
assembler test-suite/div.tk
assembler test-suite/and.tk
assembler test-suite/or.tk
assembler test-suite/xor.tk
assembler test-suite/not.tk
assembler test-suite/shftr.tk
assembler test-suite/shftri.tk
assembler test-suite/shftl.tk
assembler test-suite/shftli.tk
assembler test-suite/br.tk
assembler test-suite/brr1.tk
assembler test-suite/brr2.tk
assembler test-suite/brnz.tk
assembler test-suite/call.tk
assembler test-suite/return.tk
assembler test-suite/brgt.tk
assembler test-suite/halt.tk
assembler test-suite/mov1.tk
assembler test-suite/mov2.tk
assembler test-suite/mov3.tk
assembler test-suite/mov4.tk
assembler test-suite/addf.tk
assembler test-suite/subf.tk
assembler test-suite/mulf.tk
assembler test-suite/divf.tk
assembler test-suite/in.tk
assembler test-suite/out.tk
assembler test-suite/clr.tk
assembler test-suite/ld.tk
assembler test-suite/push.tk
assembler test-suite/pop.tk
assembler test-suite/test1.tk