#!/usr/bin/sh
gcc -o assembler assembler.c
assembler AssemblyFiles/add.tk
assembler AssemblyFiles/addi.tk
assembler AssemblyFiles/sub.tk
assembler AssemblyFiles/subi.tk
assembler AssemblyFiles/mul.tk
assembler AssemblyFiles/div.tk
assembler AssemblyFiles/and.tk
assembler AssemblyFiles/or.tk
assembler AssemblyFiles/xor.tk
assembler AssemblyFiles/not.tk
assembler AssemblyFiles/shftr.tk
assembler AssemblyFiles/shftri.tk
assembler AssemblyFiles/shftl.tk
assembler AssemblyFiles/shftli.tk
assembler AssemblyFiles/br.tk
assembler AssemblyFiles/brr1.tk
assembler AssemblyFiles/brr2.tk
assembler AssemblyFiles/brnz.tk
assembler AssemblyFiles/call.tk
assembler AssemblyFiles/return.tk
assembler AssemblyFiles/brgt.tk
assembler AssemblyFiles/halt.tk
assembler AssemblyFiles/mov1.tk
assembler AssemblyFiles/mov2.tk
assembler AssemblyFiles/mov3.tk
assembler AssemblyFiles/mov4.tk
assembler AssemblyFiles/addf.tk
assembler AssemblyFiles/subf.tk
assembler AssemblyFiles/mulf.tk
assembler AssemblyFiles/divf.tk
assembler AssemblyFiles/in.tk
assembler AssemblyFiles/out.tk
assembler AssemblyFiles/clr.tk
assembler AssemblyFiles/ld.tk
assembler AssemblyFiles/push.tk
assembler AssemblyFiles/pop.tk
assembler AssemblyFiles/test1.tk