#!/usr/bin/sh
gcc assembler.c main.c simulator.c
a.out AssemblyFiles/add.tk
a.out AssemblyFiles/addi.tk
a.out AssemblyFiles/sub.tk
a.out AssemblyFiles/subi.tk
a.out AssemblyFiles/mul.tk
a.out AssemblyFiles/div.tk
a.out AssemblyFiles/and.tk
a.out AssemblyFiles/or.tk
a.out AssemblyFiles/xor.tk
a.out AssemblyFiles/not.tk
a.out AssemblyFiles/shftr.tk
a.out AssemblyFiles/shftri.tk
a.out AssemblyFiles/shftl.tk
a.out AssemblyFiles/shftli.tk
a.out AssemblyFiles/br.tk
a.out AssemblyFiles/brr1.tk
a.out AssemblyFiles/brr2.tk
a.out AssemblyFiles/brnz.tk
a.out AssemblyFiles/call.tk
a.out AssemblyFiles/return.tk
a.out AssemblyFiles/brgt.tk
a.out AssemblyFiles/halt.tk
a.out AssemblyFiles/mov1.tk
a.out AssemblyFiles/mov2.tk
a.out AssemblyFiles/mov3.tk
a.out AssemblyFiles/mov4.tk
a.out AssemblyFiles/addf.tk
a.out AssemblyFiles/subf.tk
a.out AssemblyFiles/mulf.tk
a.out AssemblyFiles/divf.tk
a.out AssemblyFiles/in.tk
a.out AssemblyFiles/out.tk
a.out AssemblyFiles/clr.tk
a.out AssemblyFiles/ld.tk
a.out AssemblyFiles/push.tk
a.out AssemblyFiles/pop.tk
a.out AssemblyFiles/test1.tk