#!/usr/bin/sh
gcc -o simulator simulator.c
simulator test-suite/add.tko
simulator test-suite/addi.tko
simulator test-suite/sub.tko
simulator test-suite/subi.tko
simulator test-suite/mul.tko
simulator test-suite/div.tko
simulator test-suite/and.tko
simulator test-suite/or.tko
simulator test-suite/xor.tko
simulator test-suite/not.tko
simulator test-suite/shftr.tko
simulator test-suite/shftri.tko
simulator test-suite/shftl.tko
simulator test-suite/shftli.tko
simulator test-suite/br.tko
simulator test-suite/brr1.tko
simulator test-suite/brr2.tko
simulator test-suite/brnz.tko
simulator test-suite/call.tko
simulator test-suite/return.tko
simulator test-suite/brgt.tko
simulator test-suite/halt.tko
simulator test-suite/mov1.tko
simulator test-suite/mov2.tko
simulator test-suite/mov3.tko
simulator test-suite/mov4.tko
simulator test-suite/addf.tko
simulator test-suite/subf.tko
simulator test-suite/mulf.tko
simulator test-suite/divf.tko
simulator test-suite/in.tko
simulator test-suite/out.tko
simulator test-suite/clr.tko
simulator test-suite/ld.tko
simulator test-suite/push.tko
simulator test-suite/pop.tko
simulator test-suite/test1.tko