#!/usr/bin/sh
gcc -o simulator simulator.c
simulator AssemblyFiles/add.tko
simulator AssemblyFiles/addi.tko
simulator AssemblyFiles/sub.tko
simulator AssemblyFiles/subi.tko
simulator AssemblyFiles/mul.tko
simulator AssemblyFiles/div.tko
simulator AssemblyFiles/and.tko
simulator AssemblyFiles/or.tko
simulator AssemblyFiles/xor.tko
simulator AssemblyFiles/not.tko
simulator AssemblyFiles/shftr.tko
simulator AssemblyFiles/shftri.tko
simulator AssemblyFiles/shftl.tko
simulator AssemblyFiles/shftli.tko
simulator AssemblyFiles/br.tko
simulator AssemblyFiles/brr1.tko
simulator AssemblyFiles/brr2.tko
simulator AssemblyFiles/brnz.tko
simulator AssemblyFiles/call.tko
simulator AssemblyFiles/return.tko
simulator AssemblyFiles/brgt.tko
simulator AssemblyFiles/halt.tko
simulator AssemblyFiles/mov1.tko
simulator AssemblyFiles/mov2.tko
simulator AssemblyFiles/mov3.tko
simulator AssemblyFiles/mov4.tko
simulator AssemblyFiles/addf.tko
simulator AssemblyFiles/subf.tko
simulator AssemblyFiles/mulf.tko
simulator AssemblyFiles/divf.tko
simulator AssemblyFiles/in.tko
simulator AssemblyFiles/out.tko
simulator AssemblyFiles/clr.tko
simulator AssemblyFiles/ld.tko
simulator AssemblyFiles/push.tko
simulator AssemblyFiles/pop.tko
simulator AssemblyFiles/test1.tko