.code
	add r0, r1, r3
	sub r0, r3, r4
	ld r5, :L1
	br r5
; the above two instructions are for illustration only
.data
:N0
	32
	3
.code
:L1
; the following instruction is actually a macro, it loads r6 with the address specified by :N0
; please observe that the content of memory at the address :N0 is not loaded into r6, just
; the address
	ld r6, :N0
	addi r8, 1
	mov r7, (r6)(0)
	out r8, r7
	halt
; This program should print 32
; end of the program
